"""auto generate votes table

Revision ID: 167a7e1e2dac
Revises: 6a7cf9125cbd
Create Date: 2022-01-13 02:16:28.500588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167a7e1e2dac'
down_revision = '6a7cf9125cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
